version: '3'
services:
  notary:
    volumes:
      - ./build/nodes/Notary/node.conf:/etc/corda/node.conf
      - ./build/nodes/Notary/certificates:/opt/corda/certificates
      - ./build/nodes/Notary/logs:/opt/corda/logs
      - ./build/nodes/Notary/persistence:/opt/corda/persistence
      - ./build/nodes/Notary/cordapps:/opt/corda/cordapps
      - ./build/nodes/Notary/network-parameters:/opt/corda/network-parameters
      - ./build/nodes/Notary/additional-node-infos:/opt/corda/additional-node-infos
      - ./build/nodes/Notary/drivers:/opt/corda/drivers
    ports:
      - 10002:10002
    image: corda/corda-zulu-java1.8-4.4:latest
  partya:
    volumes:
      - ./build/nodes/CreditSuisse/node.conf:/etc/corda/node.conf
      - ./build/nodes/CreditSuisse/certificates:/opt/corda/certificates
      - ./build/nodes/CreditSuisse/logs:/opt/corda/logs
      - ./build/nodes/CreditSuisse/persistence:/opt/corda/persistence
      - ./build/nodes/CreditSuisse/cordapps:/opt/corda/cordapps
      - ./build/nodes/CreditSuisse/network-parameters:/opt/corda/network-parameters
      - ./build/nodes/CreditSuisse/additional-node-infos:/opt/corda/additional-node-infos
      - ./build/nodes/CreditSuisse/drivers:/opt/corda/drivers
    ports:
      - 10005:10005
      - 10024:2222
    image: corda/corda-zulu-java1.8-4.4:latest
  partyb:
    volumes:
      - ./build/nodes/JPMorgan/node.conf:/etc/corda/node.conf
      - ./build/nodes/JPMorgan/certificates:/opt/corda/certificates
      - ./build/nodes/JPMorgan/logs:/opt/corda/logs
      - ./build/nodes/JPMorgan/persistence:/opt/corda/persistence
      - ./build/nodes/JPMorgan/cordapps:/opt/corda/cordapps
      - ./build/nodes/JPMorgan/network-parameters:/opt/corda/network-parameters
      - ./build/nodes/JPMorgan/additional-node-infos:/opt/corda/additional-node-infos
      - ./build/nodes/JPMorgan/drivers:/opt/corda/drivers
    ports:
      - 10008:10008
      - 10034:2223
    image: corda/corda-zulu-java1.8-4.4:latest
